const articles = [
  {
    id: 1,
    date:"22-09-2025",
    title:
      "L’eau : source de richesse, pouvoir et de conflits",
    text1:
      "​Tous les pays ne sont pas égaux face à l’accès à l’eau, alors même qu’elle est un bien commun. On le voit de par la distribution inégale des rivières, des lacs, des installations en eau potable ou la richesse des nappes phréatiques des pays. En 2022, ce sont surtout les pays d’Afrique centrale, d'Asie de l’Est et du Sud qui souffrent plus des obstacles à l’accès à l’eau puisque plus de 1 million de leur population ne bénéficient pas d’installation en eau potable. Ces mêmes pays seront d’ailleurs de plus en plus exposés au stress hydrique d’ici 2040. Pour pallier à ce problème, il faut d’abord en connaître ses conditions d’apparition : changement climatique lié aux sécheresses et inondations, croissance démographique, manque de projets d’installations en eau potable. C’est dans ces contextes socio-environnementaux que les barrages apparaissent comme la solution permettant d’anticiper le problème du manque d’eau. Ils permettent aux États de reprendre la main sur l’eau en créant des réserves, que ce soit pour l’irrigation (48 % des barrages à but unique), l’hydroélectricité (17 %), l’approvisionnement en eau (13 %), le contrôle des crues (10 %), données de fin 2024.",
    subtitle1:
      "L’EAU FACTEUR DE PUISSANCE",
    text2:
    "​Un travail de la Banque mondiale datant de 2022 a démontré la relation positive existant entre l'évolution des réserves en eau et la croissance économique. Selon l’organisation, la croissance sous-entend une demande plus accrue en eau, et, dès lors que s’observe une diminution de l’eau, cela « se traduit par un ralentissement de la croissance ». En tant que « facteur vital », l’eau est nécessaire pour soutenir les pays en voie de développement. ​La Chine apparaît, pour ces États, comme un partenaire de choix pour la construction de barrages, on en retrouve d’ailleurs beaucoup sur le fleuve Lancang-Mékong. Une collaboration avec les pays d’Asie du Sud-Est qui s’inscrit dans les nouvelles routes de la soie et qui bénéficie non seulement au pays d’accueil de ces projets de construction (plus grande autonomie et sécurité énergétique, création d’emploi, formation de locaux), mais aussi à la Chine qui récolte les bénéfice de baux de long-terme ou des droits d’exploitation comme au Laos. De plus, ces infrastructures hydrauliques permettent de créer un marché régional attractif où la Chine, la Thaïlande et le Vietnam sont les principaux importateurs d’énergie hydraulique, alors que le Cambodge, le Laos et le Myanmar sont les principaux exportateurs. Ces projets près de la frontière chinoise permet d’accroître la connectivité entre le pays et ses voisins du sud-est. Ces projets sont aussi soutenus par la Banque Asiatique de Développement. ​L’eau permet aussi aux pays en pleine croissance, comme aux Émirats Arabes Unis où, en moyenne, chaque habitant consomme chaque jour 550L d’eau contre 870 L/jour pour un habitant de Las Vegas (250L/jour pour la moyenne mondiale).Dans les sociétés innovantes et de plus en plus connectées et urbanisées, la demande en eau ne fait que s’accroître. Il faut bien rafraîchir les data-centers qui sont plus nombreux, notamment du fait du boom de l’intelligence artificielle. L’Agence internationale de l'énergie (AIE) estime, dans son dernier rapport Energy and AI, publié en avril 2025, que les data centers ont consommé environ 560 milliards de litres d’eau à l’échelle mondiale en 2023. Un chiffre qui, selon eux, pourrait plus que doubler d’ici à 2030, pour atteindre près de 1 200 milliards de litres par an (source).",
    subtitle2:
    "L’EAU ÉCHAUDÉE",
    text3:
    "La construction de ces barrages apparaît d’une part, comme une aubaine tant économique qu’énergétique pour les pays en voie de développement ou en croissance accrue. D’autre part, ils présentent une opportunité d’influence pour les bailleurs de fonds des projets de construction. Malgré tout, les barrages génèrent des tensions dans la mesure où leur existence engendre des conséquences sur les économies voisines et dans la région. ​Du fait qu’elle est une ressource vitale, l’eau est un levier stratégique sur lequel un adversaire peut s’appuyer pour atteindre une nation. La destruction du barrage de Kakhovka en 2023 par la Russie (selon le Parlement Européen) ou par l’Ukraine (selon la Russie) affecte tant les populations et l’agriculture de Crimée, que la centrale nucléaire de Zaporijia qui utilisait le réservoir pour son système de refroidissement. ​Dans le cas du différend entre le l’Éthiopie, le Soudan et l’Égypte, l’eau n’est pas un moyen d’affecter un autre pays (car ces états ne sont pas en guerre), mais elle est, elle-même, une source de tensions. À l’origine de la dispute : la construction du grand barrage de la Renaissance menée par l’Éthiopie depuis 2011, et finalisée cette année. La présence d’une telle infrastructure sur le Nil bleu (source éthiopienne du Nil) affecte les apports en eau en Égypte et au Soudan. D’autant plus que les pays voisins de l’Éthiopie nourrissent un désaccord sur le prélèvement et le remplissage du réservoir (les éthiopiens optant pour un remplissage plus rapide que les autres). Citons aussi, dans le cas de l’eau génératrice de conflit, celui de la guerre de l’eau entre le Pakistan et l’Inde, encore d’actualité en 2025 alors qu’un traité de distribution a été conclu entre les deux pays en 1960. La situation est si critique que la Banque mondiale, qui a organisé les négociations pour le traité de 1960, finance des projets de barrages de recharge dans ces deux pays identifiés comme étant très vulnérables aux sécheresses.",
    subtitle3:
    "ASPECT ÉCONOMIQUE",
    text4:
    "​Là où la distribution de l’eau est un sujet qui nourrit des tensions entre certains États, elle permet à d’autres (via les barrages ou le contrôle sur les cours d’eau, les infrastructures) d’en tirer des bénéfices économiques et énergétiques. Dans ce domaine, la Chine excelle puisqu’en 2021 elle représente 30,1 % de la production d’électricité hydraulique mondiale. Le Brésil, qui a construit le plus grand barrage en Angola, se classe deuxième, produisant 9,2 % de l’électricité hydraulique mondiale (63,5 % à l’échelle brésilienne). ​En plus d’être liés à des marchés (celui de l’énergie, de la construction), les barrages apparaissent comme une solution quant aux entraves au commerce maritime. C’est le cas au canal de Panama, où transite 6 % du commerce mondial, puisque le passage est compromis du fait du changement climatique. C’est-à-dire que les plus gros navires ne peuvent passer que par le centre du canal et cela s’empire d’année en année. Afin de résoudre ce problème, le gouvernement du Panama souhaite construire un barrage sur le Rio Indio pour assurer d’avantage de transits. Ce projet entend aussi offrir une solution face aux sécheresses de plus en plus fréquentes, afin de sécuriser la vie des locaux. Cela dit, la réalisation sous-entend le déplacement de population.",
    subtitle5:
    "ENVIRONNEMENT",
    text5:
    "​Si les barrages apparaissent comme la solution de premier choix, elle est toutefois limités. Ces constructions s’avèreraient bien être une fausse bonne idée : une fois installées sur un cours de rivière, elles favorisent en effet l’évaporation. Par exemple, à Madagascar, Action Contre la Faim en a bien pris note et a donc mis en place un ingénieux système de barrage de sable. Le sable permet non seulement de filtrer naturellement l’eau mais aussi de réduire l’effet d’évaporation de 80 % par rapport à un barrage classique. En effet, l’eau est une denrée renouvelable dans une certaine mesure puisqu’environ la moitié de l’eau de pluie s’évapore. Depuis 2022 l’ONU prévient d'une crise imminente de l’eau tout en soulignant la gravité des périodes de sécheresse. Selon le World Resources Institute, la moitié de la population mondiale subit déjà un stress hydrique « élevé » au moins un mois par an ; et au Moyen-Orient ou en Afrique du Nord, 83 % de la population est exposée à un stress hydrique très important. ​Cette solution de trois barrages de sable à Madagascar s’avère peu coûteuse mais reste une réponse locale qui permet à un village de vivre de son agriculture, de cuisiner et de boire ; ceci alors que la population mondiale s’urbanise. ​S’ils répondent à des risques environnementaux, les barrages peuvent également en créer, notamment lorsqu’ils sont mal entretenus ou exposés à des catastrophes naturelles comme des séismes (risque d’éboulement, d’inondation, de tsunami).",
    sources:
    ""

  },
  {
    id: 2,
    date:"27-08-2025",
    title:
      "Sociétés militaires privées : symptôme de l’externalisation de la guerre.",
    text1:
      "​Le temps du monopole de la violence légitime alloué aux États est révolu. Les États ne s’appuient pas que sur des acteurs externes pour renforcer leur compétitivité dans le monde de l’innovation technologique. Les gouvernements font aussi appel à des acteurs externes issus du milieu sensible qu’est la défense. Ici, il est question de s’intéresser au phénomène d’externalisation des activités d’interventions militaires via des sociétés militaires privées (SMP). Si le mercenariat peut être confondu avec les SMP, cela dit le premier est illégal, le second est reconnu par la communauté internationale. Les mercenaires ne bénéficient pas d’un statut protégé par les conventions de Genève (Protocole additionnel aux conventions de Genève, 1977). Ces derniers ne sont pas liés à une armée régulière et les combattants agissent selon des motivations individuelles, souvent pécuniaires, pour le compte d’un État qui les embauche. Tant des critères qui peuvent s’appliquer aux employés de SMP, complexifiant ainsi leur distinction. ​A l’instar des SMP, elles sont encadrées de manière non contraignante par le document de Montreux (2008), qui adresse aux signataires quelques recommandations quant aux obligations de ces entités. ​L’appel à ces entreprises privées pour la réalisation d’opérations, autrefois domaine de chasse gardée des États, s’inscrit dans un contexte de transformation de la guerre vers une forme hybride. Face ces changements, la France doit s’adapter : ​« L’externalisation est devenue une réalité. Certaines de nos armées pratiquent la sous-traitance, la privatisation pour des opérations cinétiques ou tout simplement pour la protection armée en zone à risques. La France avait évoqué l’idée de travailler dans ce sens. Le rapport des deux députés Jean-Claude Viollet et Christian Ménard date de février 2012. En dix ans, nous n’avons pas beaucoup avancé sur la manière d’investir dans le champ des entreprises de services de sécurité et de défense – SMP, société militaire privée. » (source) ​Le guide sur l’externalisation définit l’externalisation en tant qu’« opération contractuelle impliquant un partenariat plus ou moins étroit, par lequel un organisme de la Défense décide de confier ou de transférer avec obligation de résultat à une structure externe au département une fonction, un service ou une activité qu'il assurait antérieurement, ce qui peut parfois impliquer des transferts d'actifs ».",
    subtitle1:
      "Historique",
    text2:
    "Ce phénomène d'externalisation, qui sous-entend la privatisation et la contractualisation partielle de la guerre, est en expansion, notamment depuis la chute du bloc soviétique. La première forme de SMP est apparue en Afrique du Sud, en 1989 (Exécutive Outcomes). Une entreprise qui mène, dès 1992, des opérations de sécurisation auprès des firmes pétrolières situées en Angola. C’est aussi sur le continent africain que la plus connue des SMP, Wagner, a permis à la Russie de nourrir une certaine influence. Sous Gorbatchev, puis sous Eltsine, la priorité politique était de se concentrer sur la nation, et non sur des opérations extérieures en Afrique jugées trop coûteuses. L’utilisation des SMP est répandue et n’est pas attribuable uniquement aux régimes non-démocratiques. On les retrouve au sein des USA (Blackwater), en Ukraine (Antonov logistics SALIS, une SMP qui a permis à complété les rangs des forces françaises opérant pour Serval et Barkhane). ​La Chine, état unitaire, y a également recours. Cela dit, le pays fait figure de contradiction face au paysage des SMP occidentales. Premièrement parce que leur coût est plus faible, en comparaison aux entreprises de sécurité étrangères. Comme le fait Gazprom avec Fakel et Flamya, la Chine envoie ces forces privées afin de sécuriser ses activités économiques, autour de ses nouvelles routes de la soie. Si la Chine a légalisé les activités des SMP en 2011, ce n’est toujours pas le cas pour la Russie, qui ne reconnaît pas sa proximité avec le groupe Wagner. ​Dans le cas chinois, la guerre ne se privatise pas, l’État ne laisse pas la main à des acteurs privés concernant son complexe militaro-industriel. C’est même l’inverse du phénomène d’externalisation qui s’y produit : le contrôle étatique s’étend sur les activités privées (collectivisme). Dans les états occidentaux (à tendance individualiste), les entreprises du domaine technologique ou militaro-industriel sont en droit de conserver leur position politique vis-à-vis de faits internationaux. ​L’externalisation laisse la place à l’intervention d’acteurs privés, cela contribue à la libéralisation de la guerre au sens où, sauf contre-indication de l’ONU ou nationale, les entreprises peuvent toujours contracter avec des nations étrangères. Le mouvement inverse (la nationalisation d’activités privées) suscite des tensions. Cela a été le cas lors de la nationalisation du canal de Suez sous Nasser, qui a eu pour effet de voir intervenir militairement français et anglais. Autre exemple : la crainte et la méfiance grandissante des USA envers l'’'Indonésie de Sukarno, étant donné que celui-ci entend nationaliser les activités pétrolières en 1945.",
    subtitle2:
    "Cause de l’externalisation",
    text3:
    "L’externalisation que l’on constate dans les interventions en temps de guerre s’explique par plusieurs facteurs : ​Premièrement par la politique du « war from behind », un concept renvoyant à la participation états-unienne lors de l’intervention multilatérale en Libye en 2011, et qui traduit une volonté politique de faire la guerre discrètement. Cette stratégie permet de préserver l’image d’un pays, les gouvernements n’envoient pas ses « garçons » au front, comme ce fut le cas lors de la guerre du Vietnam. Lorsque sont envoyés des contractuels, professionnels de la guerre, le gouvernement se garde l’option de ne pas reconnaître leur responsabilité sur leurs agissements. On assiste donc à l’avènement des guerres par procuration où l’on ne fait pas la guerre mais où on fait faire la guerre. Cela se traduit par l’envoi de matériel, de formateurs militaires, de financement (comme le fait l’Iran avec le Hezbollah). De plus, les revenus que les SMP génèrent en mission à l’étranger peuvent servir à l’effort de guerre national. C’est le cas de Wagner, qui réserve une partie de ses dépenses pour équiper ses hommes positionnés en Ukraine. Aussi par élan de patriotisme, de nombreux combattants de Wagner ont, à la mort de leur chef Prigojine, rejoint la Garde nationale. ​Secondement, la raison économique. Les États auraient recours aux contractuels par nécessité plutôt que par volonté. Le manque de personnel et des questions budgétaires contraignent la France à se tourner vers l’option de l’externalisation au début du XXIᵉ siècle.C’est-à-dire que suite à l’implosion du bloc soviétique, les États réduisent leur budget alloué à la défense, c’est le cas non seulement de la France, mais également des USA et du Royaume-Uni. Ainsi, dans la France sous Mitterrand, on préfère investir dans le  welfare plutôt que dans le warfare. ​Troisièmement, la raison contextuelle « d’instabilité mondiale et de préparation à la haute intensité » où « les États membres de l’OTAN se doivent de multiplier leurs capacités militaires malgré les contraintes budgétaires inhérentes aux crises successives qui ont frappé le monde (Covid-19) et l’Europe plus spécifiquement (énergie) » (source). En d’autres termes, depuis la crise de l’État-nation (Bertrand Badie), les États se doivent de recourir à d’autres moyens pour maintenir leur pouvoir, ces autres moyens incluant les acteurs externes, dont les SMP.",
    subtitle3:
    "Les problèmes de la zone grise",
    text4:
    "​Même s’il existe le document de Montreux, et que certains États ont légalisé les SMP, ces dernières n’en restent pas moins des entités peu transparentes. Déjà, parce que leurs activités s’apparentent souvent à celles du mercenariat. Par ailleurs, il existe très peu de données officielles et précises sur leur activité, leur composition, leur lieu d’opération, leur contrat et revenu. ​Enfin se pose la question de la responsabilité quant à leurs actes. Qui est responsable des exactions commises par une SMP opérant à l’étranger et qui n’est pas reconnue par son pays d’origine ? Voir l’article de Forbidden Stories sur « les prisons secrètes » de Wagner au Mali.",
    subtitle5:
    "Externalisation économique",    
    text5:
    "​Le contrat que les SMP passent avec l’État est un contrat gagnant-gagnant assurant rémunération aux contractuels et une intervention discrète pour le gouvernement. Les SMP ne sont pas les seuls acteurs externes, symptôme de l’externalisation de la guerre. Il y a les entreprises de l’armement assez influents pour soutenir des projets et stratégies de défense nationale (comme l’ont fait les nombreuses nouvelles entreprises du drone en Ukraine), mais aussi pour remporter des appels d’offres émis par des États étrangers. Citons le français Thales et le belge Proximus qui, cet été 2025, remportent l’offre de modernisation de l'agence d'information et de communication de l’Otan. Ou encore MSubs, une entreprise britannique qui a développé le drone sous-marin surnommé Excalibur que la Royal Navy a testé à l’été 2025, depuis l’Australie. Ce marché de l’armement permet à toutes nations de se doter, si elles en ont les moyens, des équipements militaires performants. Parfois, dans un contrat de vente, l’État acheteur est en mesure de bénéficier du transfert de technologie du matériel, des ressources qui lui permet de construire sur son sol ses propres équipements. ​Le monde du renseignement est également investi par des acteurs privés qui opèrent pour les gouvernements. Palantir en est un exemple. L’entreprise nord-américaine fournit des services (outils d’analyse quantité massive de données, de détection de combattants sur images de drones par exemple) à des services de renseignement étrangers (dont la DGSI) et des services états-uniens. ​La guerre dans le monde post guerre froide est également celle se jouant entre des acteurs privés dotés de moyens financiers, de brevets et de technologies précieuses pour les États. C’est ainsi que, dans le but de protéger ses savoirs, les États-Unis de Trump restreignaient en 2020 l’arrivée d’étudiants chinois dans les universités du pays (suspension et révocation de visa). La justification de cette mesure tient dans la considération de la civil-military fusion strategy. Une façon de pensée à la chinoise, qui vise à envisager la recherche en termes de double-avancée, dans les domaines économique et militaire. L’affrontement des avancées en matières d’innovation s’observe actuellement dans le domaine de l’intelligence artificielle, une course au « meilleur »  qui rappelle la course à l’espace du temps où le monde se divisait en deux",
    sources:
    "À lire : https://www.portail-ie.fr/univers/enjeux-de-puissances-et-geoeconomie/2023/lexternalisation-des-fonctions-de-soutien-de-larmee-une-tendance-qui-questionne-sur-notre-independance-strategique-a-long-terme/"
    
  }

];

export { articles };